-- MySQL Script generated by MySQL Workbench
-- Fri Nov 21 15:55:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dw_proyectos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dw_proyectos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dw_proyectos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dw_proyectos` ;

-- -----------------------------------------------------
-- Table `dw_proyectos`.`dim_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_proyectos`.`dim_clientes` (
  `ID_Cliente` INT NOT NULL AUTO_INCREMENT,
  `CodigoClienteReal` INT NOT NULL,
  PRIMARY KEY (`ID_Cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dw_proyectos`.`dim_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_proyectos`.`dim_empleados` (
  `ID_Empleado` INT NOT NULL AUTO_INCREMENT,
  `CodigoEmpleado` INT NOT NULL,
  `Rol` VARCHAR(100) NULL DEFAULT NULL,
  `Seniority` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dw_proyectos`.`dim_gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_proyectos`.`dim_gastos` (
  `ID_Finanza` INT NOT NULL AUTO_INCREMENT,
  `TipoGasto` VARCHAR(50) NOT NULL,
  `Categoria` VARCHAR(20) NULL DEFAULT NULL,
  `Monto` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`ID_Finanza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dw_proyectos`.`dim_proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_proyectos`.`dim_proyectos` (
  `ID_Proyecto` INT NOT NULL AUTO_INCREMENT,
  `CodigoProyecto` INT NOT NULL,
  `Version` INT NULL DEFAULT NULL,
  `Cancelado` TINYINT(1) NULL DEFAULT '0',
  `ID_Cliente` INT NULL DEFAULT NULL,
  `TotalErrores` INT NULL,
  `NumTrabajadores` INT NULL,
  PRIMARY KEY (`ID_Proyecto`),
  INDEX `ID_Cliente` (`ID_Cliente` ASC) VISIBLE,
  CONSTRAINT `dim_proyectos_ibfk_1`
    FOREIGN KEY (`ID_Cliente`)
    REFERENCES `dw_proyectos`.`dim_clientes` (`ID_Cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dw_proyectos`.`dim_tiempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_proyectos`.`dim_tiempo` (
  `ID_Tiempo` INT NOT NULL AUTO_INCREMENT,
  `Dia` INT NULL DEFAULT NULL,
  `Mes` INT NULL DEFAULT NULL,
  `Anio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Tiempo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dw_proyectos`.`dim_hitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_proyectos`.`dim_hitos` (
  `ID_Hito` INT NOT NULL AUTO_INCREMENT,
  `CodigoHito` INT NOT NULL,
  `ID_proyectos` INT NULL DEFAULT NULL,
  `ID_FechaInicio` INT NULL DEFAULT NULL,
  `ID_FechaFin` INT NULL DEFAULT NULL,
  `RetrasoInicioDias` INT NULL DEFAULT NULL,
  `RetrasoFinDias` INT NULL,
  PRIMARY KEY (`ID_Hito`),
  INDEX `ID_proyectos` (`ID_proyectos` ASC) VISIBLE,
  INDEX `ID_FechaInicio` (`ID_FechaInicio` ASC) VISIBLE,
  INDEX `ID_FechaFinalizacion` (`ID_FechaFin` ASC) VISIBLE,
  CONSTRAINT `dim_hitos_ibfk_1`
    FOREIGN KEY (`ID_proyectos`)
    REFERENCES `dw_proyectos`.`dim_proyectos` (`ID_Proyecto`),
  CONSTRAINT `dim_hitos_ibfk_2`
    FOREIGN KEY (`ID_FechaInicio`)
    REFERENCES `dw_proyectos`.`dim_tiempo` (`ID_Tiempo`),
  CONSTRAINT `dim_hitos_ibfk_3`
    FOREIGN KEY (`ID_FechaFin`)
    REFERENCES `dw_proyectos`.`dim_tiempo` (`ID_Tiempo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dw_proyectos`.`dim_pruebas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_proyectos`.`dim_pruebas` (
  `ID_Prueba` INT NOT NULL AUTO_INCREMENT,
  `CodigoPrueba` INT NOT NULL,
  `ID_Hito` INT NOT NULL,
  `TipoPrueba` VARCHAR(50) NOT NULL,
  `PruebaExitosa` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Prueba`),
  INDEX `ID_Hito` (`ID_Hito` ASC) VISIBLE,
  CONSTRAINT `dim_pruebas_ibfk_1`
    FOREIGN KEY (`ID_Hito`)
    REFERENCES `dw_proyectos`.`dim_hitos` (`ID_Hito`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dw_proyectos`.`dim_tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_proyectos`.`dim_tareas` (
  `ID_Tarea` INT NOT NULL AUTO_INCREMENT,
  `CodigoTarea` INT NOT NULL,
  `ID_Hito` INT NOT NULL,
  `SeRetraso` TINYINT NULL,
  PRIMARY KEY (`ID_Tarea`),
  INDEX `ID_Hito` (`ID_Hito` ASC) VISIBLE,
  CONSTRAINT `dim_tareas_ibfk_1`
    FOREIGN KEY (`ID_Hito`)
    REFERENCES `dw_proyectos`.`dim_hitos` (`ID_Hito`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dw_proyectos`.`hechos_asignaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_proyectos`.`hechos_asignaciones` (
  `ID_HechoAsignacion` BIGINT NOT NULL AUTO_INCREMENT,
  `ID_Empleado` INT NOT NULL,
  `ID_Proyecto` INT NOT NULL,
  `ID_FechaAsignacion` INT NOT NULL,
  `HorasPlanificadas` INT NULL DEFAULT '0.00',
  `HorasReales` INT NULL DEFAULT '0.00',
  `ValorHoras` DECIMAL(15,2) NULL DEFAULT NULL,
  `RetrasoHoras` INT NULL,
  PRIMARY KEY (`ID_HechoAsignacion`),
  INDEX `ID_Empleado` (`ID_Empleado` ASC) VISIBLE,
  INDEX `ID_Proyecto` (`ID_Proyecto` ASC) VISIBLE,
  INDEX `ID_FechaAsignacion` (`ID_FechaAsignacion` ASC) VISIBLE,
  CONSTRAINT `hechos_asignaciones_ibfk_1`
    FOREIGN KEY (`ID_Empleado`)
    REFERENCES `dw_proyectos`.`dim_empleados` (`ID_Empleado`),
  CONSTRAINT `hechos_asignaciones_ibfk_2`
    FOREIGN KEY (`ID_Proyecto`)
    REFERENCES `dw_proyectos`.`dim_proyectos` (`ID_Proyecto`),
  CONSTRAINT `hechos_asignaciones_ibfk_3`
    FOREIGN KEY (`ID_FechaAsignacion`)
    REFERENCES `dw_proyectos`.`dim_tiempo` (`ID_Tiempo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dw_proyectos`.`hechos_proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_proyectos`.`hechos_proyectos` (
  `ID_Hecho` BIGINT NOT NULL AUTO_INCREMENT,
  `ID_Proyecto` INT NOT NULL,
  `ID_Riesgo` INT NULL DEFAULT NULL,
  `ID_Gasto` INT NULL DEFAULT NULL,
  `ID_FechaInicio` INT NULL,
  `ID_FechaFin` INT NULL,
  `RetrasoInicioDias` INT NULL DEFAULT '0',
  `RetrasoFinalDias` INT NULL,
  `Presupuesto` FLOAT NOT NULL,
  `CosteReal` FLOAT NULL DEFAULT '0.00',
  `DesviacionPresupuestal` FLOAT NULL DEFAULT '0.00',
  `PenalizacionesMonto` FLOAT NULL DEFAULT '0.00',
  `ProporcionCAPEX_OPEX` FLOAT NULL DEFAULT NULL,
  `TasaDeErroresEncontrados` FLOAT NULL DEFAULT '0',
  `TasaDeExitoEnPruebas` FLOAT NULL,
  `ProductividadPromedio` FLOAT NULL DEFAULT NULL,
  `PorcentajeTareasRetrasadas` FLOAT NULL DEFAULT '0.00',
  `PorcentajeHitosRetrasados` FLOAT NULL DEFAULT '0.00',
  PRIMARY KEY (`ID_Hecho`),
  INDEX `ID_Proyecto` (`ID_Proyecto` ASC) VISIBLE,
  INDEX `ID_Finanza` (`ID_Gasto` ASC) VISIBLE,
  INDEX `fechainicio_idx` (`ID_FechaInicio` ASC) VISIBLE,
  INDEX `fechafin_idx` (`ID_FechaFin` ASC) VISIBLE,
  CONSTRAINT `hechos_proyectos_ibfk_1`
    FOREIGN KEY (`ID_Proyecto`)
    REFERENCES `dw_proyectos`.`dim_proyectos` (`ID_Proyecto`),
  CONSTRAINT `hechos_proyectos_ibfk_5`
    FOREIGN KEY (`ID_Gasto`)
    REFERENCES `dw_proyectos`.`dim_gastos` (`ID_Finanza`),
  CONSTRAINT `fechainicio`
    FOREIGN KEY (`ID_FechaInicio`)
    REFERENCES `dw_proyectos`.`dim_tiempo` (`ID_Tiempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fechafin`
    FOREIGN KEY (`ID_FechaFin`)
    REFERENCES `dw_proyectos`.`dim_tiempo` (`ID_Tiempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
